### ISSUE TITLE
main page - create endpoint to consume external serviceses

### ISSUE THREAD

**Issue by ArceDaniel** [cloudinary-hackathon/proyect#1]
Objetivo: Desarrollar un endpoint que reciba los datos del primer formulario y devuelva las URLs de las imágenes procesadas como respuesta.

Tarea:

- Recibir imágenes y subirlas a Cloudinary.
- Pasar las imágenes por el servicio de Gen Background Replace API para reemplazar el fondo según la temática seleccionada.

Input esperado:

- Imágenes (archivo).
- Tema (enum).
- Descripción (string).

Output esperado:

- ID de las imágenes.
- URL de las imágenes procesadas.

![image](https://github.com/user-attachments/assets/a3f7a197-292a-4687-853f-42b30c652b0e)

**Comment by yocxy2** [comment]
no se si este comentario se vea ..prueba para ver cambios
