### ISSUE TITLE
main page - consume endpoint to main page

### ISSUE THREAD

**Issue by ArceDaniel** [cloudinary-hackathon/proyect#2]
**Objetivo:** Crear funciones asíncronas que realicen las llamadas a nuestros endpoints, enviando los datos del primer formulario. El objetivo es abstraer la responsabilidad de la lógica en la página y simplificar su uso.

**Tareas:**
1. Implementar el uso del endpoint para reemplazar el fondo de las imágenes.
2. Implementar el uso del endpoint para generar la historia de las imágenes.

![image](https://github.com/user-attachments/assets/c89c80df-398c-4146-8e2a-ebf7be7748d0)

**Comment by yocxy2** [comment]
como va esta tarea?
